#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page" > /var/www/html/404.html

echo "
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  root /var/www/html;
  index index.html;

  error_page 404 /404.html;
  location = /404.html {
    root /var/www/html;
    internal;
  }

  rewrite ^/redirect_me https://google.com permanent;
}
" > /etc/nginx/sites-available/default

service nginx restart
