#!/usr/bin/env bash
# Install and configure HAproxy on server

sudo apt-get update

sudo apt-get install haproxy -y

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

echo "
frontend www
	bind :80
	option http-server-close
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 161403-web-01 100.26.221.167:80 check
	server 161403-web-02   52.72.35.225:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
