#!/usr/bin/env bash
# Install and configure HAproxy on server

apt-get update

add-apt-repository ppa:vbernat/haproxy-2.6 -y

apt-get update
apt-get install haproxy=2.6.\* -y

systemctl enable haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

echo "
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 161403-web-01 100.26.221.167:80 check
    server 161403-web-02 52.72.35.225:80 check
" >> /etc/haproxy/haproxy.cfg

systemctl restart haproxy
