#!/usr/bin/env bash
# Writes "I am alive!" to the file /tmp/my_process every 2 seconds

sudo chown "$USER":"$USER" /tmp/my_process

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
