#!/usr/bin/env bash
# Displays the content of /etc/passwd using the while loop + IFS
IFS=:
while read -r line
do
  (
    read -r uname passwd uid gid user_info home_dir cmd
    echo "The user $uname is part of the $gid gang, lives in $home_dir and rides $cmd. $uid's place is protected by the passcode $passwd, more info about the user here: $user_info"
  ) <<< "$line"
done < "/etc/passwd"
