#!/usr/bin/env bash
# Loops 10 times and displays "bad luck" for the 4th iteration, "good luck" for the 8th, and "Best School" for the other iterations.
i=1
while [ $i -le 10 ]
do
  if [ $i == 4 ]
  then
    echo "bad luck"
  elif [ $i == 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
