#!/usr/bin/env bash
# Displays the content of the current directory in list format where only the part of the name after the first dash is displayed.
for item in *
do
  echo "$item" | cut -d '-' -f 2
done
